[package]
name = "netaheuristics"
version = "0.2.0"
edition = "2021"
license = "MIT"
keywords = ["optimization", "heuristic"]
description = "Framework to create metaheuristics"
repository = "https://github.com/DaPurr/Netaheuristics"

[dependencies]
rand = "0.8"
assert_approx_eq = "1.1.0"
